### PR TITLE
rocket m series support

### PR DESCRIPTION
**Pull request by epipenau**
i created pull requests for github.com/freebsd/freebsd to merge the kernel config ROCKET_M2HP and ROCKET_M2HP.hints.  not sure if that's the correct branch to use.  correct me if not.

adrian: if you see this i'm on irc as masked.

### CODE REVIEW

**Comment by hirenp** [comment]
On Thu, Jan 8, 2015 at 5:00 AM, epipenau <notifications@github.com> wrote:

> i created pull requests for github.com/freebsd/freebsd to merge the
> kernel config ROCKET_M2HP and ROCKET_M2HP.hints. not sure if that's the
> correct branch to use. correct me if not.
>
> adrian: if you see this i'm on irc as masked.
> ------------------------------
> You can merge this Pull Request by running
>
>   git pull https://github.com/epipenau/freebsd-wifi-build master
>
> Or view, comment on, or merge it at:
>
>   https://github.com/freebsd/freebsd-wifi-build/pull/27
> Commit Summary
>
>    - rocket m series support
>
> File Changes
>
>    - *A* build/cfg/rocket_m2hp
>    <https://github.com/freebsd/freebsd-wifi-build/pull/27/files#diff-0>
>    (42)
>
> Patch Links:
>
>    - https://github.com/freebsd/freebsd-wifi-build/pull/27.patch
>    - https://github.com/freebsd/freebsd-wifi-build/pull/27.diff
>
>  Why do you name it rocket_m2hp? From: http://www.ubnt.com/airmax/rocketm/,
shouldn't rocket_m2 suffice and more correct?

Also, https://github.com/freebsd/freebsd/pull/16 in this you've combined 2
things: rocket m2 and winbond w25x64. Am I correct?

I'll take care of rocket m2 commit.

Cheers,
Hiren

**Comment by epipenau** [comment]
Hiren,
Yes.  That is correct.  As it turns out though, PICOSTATION_M2HP and ROCKET_M2HP from -HEAD do not differ.  So far I have successfully installed a PICOSTATION_M2HP image on the Ubiquiti Rocket and the Bullet, so I don't know if we want multiple config files or if we want to rename PICOSTATION_M2HP to UBNTXM.  However arge0 isn't attaching so i'm getting no ethernetworking and the random number generator isn't working properly and as a result I cannot create any hostap's with WPA enabled.  I'm just about to post some stuff in freebsd-embedded.

Date: Thu, 8 Jan 2015 13:31:18 -0800

**Comment by epipenau** [comment]
the winbond w25x64 is the flash chip on the rocket.  well at least it is on two rocket's that i have here so it's required for a rocket image to boot the rootfs, regardless if one is using the picostation config or the rocket config.

Date: Thu, 8 Jan 2015 13:31:18 -0800

**Comment by epipenau** [comment]
Hiren, did you ever commit the Winbond commit?  One cannot access the Rocket's Flash without it.

**Pull request closed without merging**
